steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build Image
  entrypoint: bash
  args:
    - -c
    - |
      docker build . -t us-east1-docker.pkg.dev/genai-playground-387506/app/github-assitant:latest \
      && docker push us-east1-docker.pkg.dev/genai-playground-387506/app/github-assitant:latest 
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  id: Deploy API
  args: ['run', 'deploy', $PROJECT_ID,
             --image=us-east1-docker.pkg.dev/genai-playground-387506/app/github-assitant:latest,
             '--region=us-east1', '--service-account=vertex-ai-consumer@genai-playground-387506.iam.gserviceaccount.com',
              '--allow-unauthenticated',
              '--set-env-vars=STREAMLIT_SERVER_PORT=80, PINECONE_INDEX_NAME=wordblend-ai-index',
              '--set-secrets=PALM2_API_KEY=PALM2_API_KEY:latest, PINECONE_API_KEY=PINECONE_API_KEY:latest,PINECONE_ENVIRONMENT_REGION=PINECONE_ENVIRONMENT_REGION:latest']
  waitFor: [ 'Build Image' ]

images:
- 'us-east1-docker.pkg.dev/genai-playground-387506/app/github-assitant:latest'